version: "3.8"

services:
  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:latest
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.99.0.2
    environment:
      UPSTREAM1: 'https://1.1.1./dns-query'
      UPSTREAM2: 'https://1.0.0.1/dns-query'
          
  googleflared:
    container_name: googleflared
    image: visibilityspots/cloudflared:latest
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.99.0.4
    environment:
      UPSTREAM1: 'https://8.8.8.8/dns-query'
      UPSTREAM2: 'https://8.8.4.4/dns-query'
          
  pi-hole:
    depends_on:
      - cloudflared
      - googleflared
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8088:80/tcp"  # Port mapping for HTTP
    environment:
      ServerIP: '10.99.0.3'
      DNS1: '10.99.0.2#5054'
      DNS2: '10.99.0.4#5054'
      IPv6: 'true'
      TZ: 'America/Los_Angeles'
      DNSMASQ_LISTENING: 'all'
      WEBPASSWORD: ${WEBPASSWORD}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    networks:
      pihole_net:
        ipv4_address: 10.99.0.3
    dns:
      - 127.0.0.1
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - './var-log/lighttpd/:/var/log/lighttpd/'  # Volume mount for lighttpd logs
    cap_add:
      - NET_ADMIN
          
networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.99.0.0/29
